[package]
name = "stamp_scraper"
version = "0.1.0"
authors = ["mike"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.13.0"
regex = "1.5"